app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class User(db.Model,UserMixin):

    '''creates instances of user
    '''
    __tablename__= 'users'

    id  = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    username = db.Column(db.String(255),unique = True,nullable=False)
    email = db.Column(db.String(255),unique = True,nullable=False)
    avatar = db.Column(db.String(200), default='default.jpg')
    pass_secure = db.Column(db.String(255))
    favorites = db.relationship('Favorites',backref = 'favorite',lazy ="dynamic")


    @property
    def password(self):
        raise AttributeError("Can't read")

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

class Places(db.Model):
    '''creates insatnces of places on the map
    '''
    __tablename__='places'

    id = db.Column(db.Integer,primary_key=True)
    place_name= db.Column(db.String(100),nullable=False)
    region = db.Column(db.String(100),nullable=False)
    description= db.Column(db.String(300),nullable=True)
    lat = db.Column(db.Float,nullable=False)
    lng = db.Column(db.Float,nullable=False)
    image = db.Column(db.String, default='default.jpg')
    reviews = db.relationship('Review',backref = 'reviews',lazy ="dynamic")
    favs = db.relationship('Favorites',backref='favorites',lazy=True)

    def save_place(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f' {self.place_name}, {self.description}'

class Favorites(db.Model):
    """Saved places as favorited by users."""

    __tablename__ = "favorite"

    id = db.Column(db.Integer,primary_key=True)
    place_id = db.Column(db.Integer, db.ForeignKey("places.id"), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)


    def save_favorite(self):
        db.session.add(self)
        db.session.commit()

class Review(db.Model):
	__tablename__ = 'reviews'
    
	id = db.Column(db.Integer, primary_key=True)
	name= db.Column(db.String(255))
	review = db.Column(db.Text)
	date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
	place_id = db.Column(db.Integer, db.ForeignKey("places.id"), nullable=False)



	def save_review(self):
		db.session.add(self)
		db.session.commit()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,IntegerField,FloatField
from wtforms.validators import Required

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
# from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
# mail = Mail()

def create_app(config_state):
    app = Flask(__name__)
    app.config.from_object(config_options[config_state])


    bootstrap.init_app(app)
    db.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    # mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    from .requests import configure_request
    configure_request(app)

    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for,abort
from . import main
from .. import db
from ..models import User,Places,Favorites
from flask_login import current_user,login_required
import json
from ..requests import create_stop_locations_details,get_from_database,get_route
from geojson import Point, Feature


@main.route('/')
def index():
   title = 'Vybe'
   return render_template('index.html',title=title)

@main.route('/profile')
@login_required
def profile():

    favorites = Favorites.query.filter_by(user_id=current_user.id).all()
    places = []
    for favorite in favorites:
        {favorite.place_id,favorite.user_id}
        place = Places.query.filter_by(id=favorite.place_id).first()
        if place not in places:
            places.append(place)

    # places = Places.query.filter_by(id = favorites.place_id).all()
    user = current_user

    title = current_user.name

    return render_template('profile.html',title=title, user = user,places=places)



@main.route('/favourites')
@login_required
def favourites():

    user = current_user

    title = current_user.name

    places = Places.query.all()

    for place in places:
        new_route = {"lat": place.lat, "long": place.lng, "name": place.place_name, "is_stop_location": True}
        get_from_database(new_route)

    return render_template('favourites.html',title=title, user = user, places = places)



@main.route('/explore')
@login_required
def home():
    title = 'Explore'

    user = current_user

    places = Places.query.all()

    for place in places:
        new_route = {"lat": place.lat, "long": place.lng, "name": place.place_name, "is_stop_location": True}
        get_from_database(new_route)

    route = get_route()

    stop_locations = create_stop_locations_details(route)

    return render_template('home.html',title=title,stop_locations=stop_locations, user = user, ACCESS_KEY='sk.eyJ1Ijoic2FiZXJkYW5nZXIiLCJhIjoiY2pzZWJjZ3JwMTI0ZDN6bWx4bHplcWl3dyJ9.8EJHp44K185MRZExZcv_Tg',places=places)

@main.route('/like/<int:id>',methods=['GET','POST'])
@login_required
def like(id): 

    place = Places.query.filter_by(id = id).first()

    has_faved = Favorites.query.filter_by(user_id=current_user.id,place_id=place.id).first()

    if has_faved:
        db.session.delete(has_faved)
        db.session.commit()
    else:
        fav = Favorites(place_id=place.id,user_id=current_user.id)
        fav.save_favorite()

    return redirect(url_for('main.favourites'))

    return render_template('favourites.html')

app/templates/base.html
{% extends 'bootstrap/base.html'%}


{{ wtf.quick_form(form) }}

app/templates/favourites.html
{% include "layout.html" %}

{% block content %}



    <div class="container">
        {% include "in-nav.html" %}
    </div>

    <div class="container">
        <h1 class='title-text'>Popular Places</h1>
    </div>
    <div class="card-pane">
        <div class="container">
            {% for place in places %}
            <div class="place-card">
                <div class="place-image">
                    <img src="{{ url_for('static', filename='places/'+place.image) }}" alt="">
                </div>
                <div class="place-details">
                    <h1>{{ place.place_name }}</h1>
                    <a href="{{ url_for('main.like', id=place.id) }}">
                        <p><i class="fas fa-heart"></i> {{ place.favs|count() }} Favorites</p>  
                    </a>  
                </div>
            </div>
            {% endfor %}
        </div>
        
        
    </div>      

{% endblock %}

app/templates/home.html
{% extends 'layout.html' %}

{% block content %}

      <div class="container">
         {% include "in-nav.html" %}
      </div>

      <div id="map"></div>
      <script>
         L.mapbox.accessToken = 'pk.eyJ1Ijoic2FiZXJkYW5nZXIiLCJhIjoiY2pzZHhnbzY3MGFwazQ0cDRjaWk0MDRwZSJ9.-5E6mGB8ehOgTYDpzJaU9Q';

         var map = L.mapbox.map('map', 'mapbox.streets', {
            scrollWheelZoom: true,
            zoomControl: true,
         }).setView([-1.2825,36.8234], 6);
         
         L.mapbox.featureLayer({{ stop_locations|safe }}).addTo(map);

      </script>


{% endblock %}

app/templates/in-nav.html
   <nav>
      <div class='logo'>
         <a href="{{ url_for('main.index') }}" class='logo'>
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="">
         </a>
      </div>
      <div class="menu right">
         <ul>
            <li class='text'><a href="{{ url_for('main.home') }}">Explore</a></li>
            <li class='text'><a href="{{ url_for('main.favourites') }}">Popular</a></li>
            <li class="avatar-tiny">
               <a href="{{ url_for('main.profile') }}">
                  <img src="{{ url_for('static', filename='avatars/'+user.avatar) }}" alt="">
               </a>
            </li>
         </ul>
      </div>
   </nav>

app/templates/index.html
{% extends 'layout.html'%}

{% block content %}
    
    <div id="page">
        <header>
            {% include "nav.html" %}
            <div class="header-text left">
                <h1>Map your favorite<br>places.</h1>
                <p>Know of any interesting places? Share them with us.</p>
                <a href="{{ url_for('auth.register') }}">
                    <button class="main-btn">Sign Up</button>
                </a>
            </div>
            <div class="person right">
                <img src="{{ url_for('static', filename='images/man.png') }}" alt="">
            </div>
        </header>
    </div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
   <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet">
   <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
   <link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.3/mapbox.css' rel='stylesheet' />
   <script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.3/mapbox.js'></script>
   <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
   <title>Vybe</title>
</head>
<body>
   
   {% block content %}
   {% endblock %}
   
</body>
</html>

app/templates/map.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Map</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<!-- map rendered here -->
<div id='map'>Pick a place</div>
<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoic2FiZXJkYW5nZXIiLCJhIjoiY2pzYnRwam1oMGRyczQ1bWxweHl4MmltdSJ9.r3PTm_k0VkCSoLtPftuwjg';
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/light-v9', //hosted style id
    center: [-77.38, 39], // starting position
    zoom: 3 // starting zoom
});
</script>

</body>
</html>

app/templates/nav.html
<nav>
   <div class='logo'>
      <a href="{{ url_for('main.index') }}">
         <img src="{{ url_for('static', filename='images/logo.png') }}" alt="">
      </a>
   </div>
   <div class="menu right">
      <ul>
         <li><a href="{{ url_for('auth.register') }}">Log In</a></li>
      </ul>
   </div>
</nav>

app/templates/profile.html
{% extends 'layout.html' %}

{% block content %}

   <div class="in-nav">
      {% include 'in-nav.html' %}
   </div>

   <div class="container">
      <div class="profile-details">
         <div class="avatar left">
            <img src="{{ url_for('static', filename='avatars/'+user.avatar) }}" alt="">
         </div>
         <div class="meta right">
            <h1>{{ user.name }}</h1>
            <p>3 Places</p>
            <a href="{{ url_for('main.favourites') }}">
               <button class="main-btn">Favourites</button>
            </a>
         </div>
      </div>
   </div>

   <div class="card-pane clear-left in-profile-card">
         <div class="container">
             {% for place in places %}
             <div class="place-card">
                 <div class="place-image">
                     <img src="{{ url_for('static', filename='places/'+place.image) }}" alt="">
                 </div>
                 <div class="place-details">
                     <h1>{{ place.place_name }}</h1>
                     <a href="{{ url_for('main.like', id=place.id) }}">
                         <p><i class="fas fa-heart"></i> {{ place.favs|count() }} Favorites</p>  
                     </a>  
                 </div>
             </div>
             {% endfor %}
         </div>
     </div>  


{% endblock %}